apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  selector:
    matchLabels:
      service: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: trannhatquang2405/udagram-api-feed:v1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 800m
            requests:
              cpu: 500m
          volumeMounts:
            - name: aws-secret
              mountPath: "/root/.aws/"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
